# I am building a PHP Chat Application.
version: '3.7' # This is the version of docker-compose.yml file.

services:
  web-server:
    # let's use nginx for this.
    image: nginx:latest
    ports:
      - "5600:80" # access at: localhost:5600
    # I need to mount the current directory to the web server. So that I can access the files in the current directory from the web server.
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf # mount the default.conf file to the web server.
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app # the app directory is mounted to the php server.